"""update posts and topic table

Revision ID: 44e10f059380
Revises: b6e80c981511
Create Date: 2021-11-24 21:42:21.457474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44e10f059380"
down_revision = "b6e80c981511"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("topic_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "posts", "topics", ["topic_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("topics_post_id_fkey", "topics", type_="foreignkey")
    op.drop_column("topics", "post_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topics",
        sa.Column("post_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key("topics_post_id_fkey", "topics", "posts", ["post_id"], ["id"])
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "topic_id")
    # ### end Alembic commands ###
