"""removes column id and values

Revision ID: 47379b6239ea
Revises: 7bcb011fdf40
Create Date: 2021-11-22 21:36:05.612871

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "47379b6239ea"
down_revision = "7bcb011fdf40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("votes", "value")
    op.drop_column("votes", "id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "votes", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "votes", sa.Column("value", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
