"""add missing column for comments table

Revision ID: 8f8234c7ebb3
Revises: 38978c695f0f
Create Date: 2021-11-24 13:47:30.836368

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8f8234c7ebb3"
down_revision = "38978c695f0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
