"""add missing relationship for comments table

Revision ID: 93d836be6f49
Revises: 8f8234c7ebb3
Create Date: 2021-11-24 13:50:08.093206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93d836be6f49"
down_revision = "8f8234c7ebb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
