"""make title unique for the topic table

Revision ID: d15b12948ec7
Revises: 44e10f059380
Create Date: 2021-11-24 22:35:23.783200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15b12948ec7'
down_revision = '44e10f059380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_topics_title'), 'topics', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_title'), table_name='topics')
    # ### end Alembic commands ###
