"""renaming column created_by

Revision ID: f310292f7eaf
Revises: 93d836be6f49
Create Date: 2021-11-24 15:20:54.475020

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f310292f7eaf"
down_revision = "93d836be6f49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
